describe('Search and user profile',() => {
    it('Search', () => {
        cy.Admin_Login()
        // cy.get('[data-link="community"]').should("be.visible").click();
        // cy.get("a.btn-new-community").invoke("removeAttr", "target").click()
        cy.visit(Cypress.env('API_URL')+"/community")
        cy.get(".feedTitle").should("be.visible");
        cy.get('.loading-wrapper').should('have.length', 0)
        cy.get('.searchInput').should('be.visible').type('DND{enter}' )
        cy.get('.searched-post-preview').should('be.visible')
        cy.get('h2').should('contain.text','Public post in public community')
        cy.get('div.searched-post-preview__search-keyword > .searched-post-preview__search-keyword').should('have.text','DND')
        cy.get('.searched-post-preview').should("be.visible").click()
        cy.get('.postPreviewRefWrapper').should("be.visible")
        cy.get('.postPreviewTitle > h1').should('contain.text','Public post in public community')
        cy.get('.closeSinglePostPopupBtn').should("be.visible").click()
    })
    it('User Profile', () => {
        cy.Admin_Login()
        // cy.get('[data-link="community"]').should("be.visible").click();
        // cy.get("a.btn-new-community").invoke("removeAttr", "target").click()
        cy.visit(Cypress.env('API_URL')+"/community")
        cy.get(".feedTitle").should("be.visible");
        cy.get('.userPreview > img').should("be.visible").click()
        cy.get('.profileWrapper').should("be.visible")
        cy.get(':nth-child(2) > .userName').should('contain.text','Pranav')
        cy.get('.activeTab').should("be.visible")
        cy.get('.recentActivity').should("be.visible")
        cy.get('.tabHeader > :nth-child(2)').should("be.visible").click()
        cy.get(':nth-child(1) > .community').should("be.visible").click()
        cy.get('body')
            .find('.profileWrapper').should('have.length', 0)
        cy.get(':nth-child(1) > .postPreview > .postHeaderSectn').should("be.visible")
        cy.wait(2000)
        cy.get('.communityTabs > :nth-child(3)').should("be.visible").click()
        cy.get(':nth-child(1) > .memberPreview > .memberInfoWrapper > .memberNameWrapper > .memberName').should("be.visible").click()
        cy.get('.profileWrapper').should("be.visible")
        cy.get(':nth-child(2) > .userName').should('contain.text','Pranav')
        cy.get('.activeTab').should("be.visible")
        cy.get('.tabHeader > :nth-child(2)').should("be.visible").click()
        cy.get(':nth-child(1) > .community').should("be.visible")
        cy.get('.closeButton').click()
        cy.get('body')
            .find('.profileWrapper').should('have.length', 0)
        cy.get('[href="/community-account/members"] > .tabWrapper').should("be.visible").click()
        cy.get('.bannedPanelTitel').should("be.visible")
        cy.get('.membersListInMembersPage').should("be.visible")
        cy.get(':nth-child(1) > .memberPreview > .memberInfoWrapper > .memberNameWrapper > .memberName').should("be.visible").click()
        cy.get('.profileWrapper').should("be.visible")
        cy.get(':nth-child(2) > .userName').should('contain.text','Pranav')
        cy.get('.activeTab').should("be.visible")
        cy.get('.tabHeader > :nth-child(2)').should("be.visible").click()
        cy.get(':nth-child(1) > .community').should("be.visible")
        cy.get('.closeButton').click()


    })

})